// <auto-generated />
namespace IT_Lab3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0-preview5-19254-05")]
    public sealed partial class FixIdColumnThird : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FixIdColumnThird));
        
        string IMigrationMetadata.Id
        {
            get { return "201905141319242_FixIdColumnThird"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
